language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

dist: trusty
sudo: true

before_script:
    - wget -P /home/travis/build/guanguans/soar-php/ https://github.com/XiaoMi/soar/releases/download/0.11.0/soar.linux-amd64
    - chmod a+x /home/travis/build/guanguans/soar-php/soar.linux-amd64
    - composer self-update
    - composer install --no-interaction --dev

script:
    - pwd
    - ./vendor/bin/phpunit --verbose --coverage-clover=coverage.xml

after_script:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email: true

matrix:
    fast_finish: true